version: "3.8"

services:
  kurkkumopo_frontend:
    build: github.com/docker-hy/ml-kurkkumopo-frontend
    ports:
      - 3000:3000
  kurkkumopo_backend:
    build: github.com/docker-hy/ml-kurkkumopo-backend
    ports:
      - 5000:5000
    volumes:
      - model:/src/model
  training:
    build: github.com/docker-hy/ml-kurkkumopo-training
    volumes:
      - imgs:/src/imgs
      - data:/src/data
      - model:/src/model

volumes:
  imgs:
  data:
  model:
