version: "3.8"

services:
  frontend:
    build:
      context: ../../material-applications/example-frontend
    ports:
      - 5000:5000
    container_name: frontend
  backend:
    build:
      context: ../../material-applications/example-backend 
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_PASSWORD=example
      - POSTGRES_HOST=db
    container_name: backend
  redis:
    image: redis
    restart: unless-stopped
  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./database:/var/lib/postgresql/data
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend
